name: lando-php74
events:
  post-start:
    - defaults: php -i | grep memory_limit | grep -e "-1"
services:
  defaults:
    type: php:7.4
  cli:
    type: php:7.4
    composer_version: 1-latest
    via: cli
    build_as_root:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      - bash -c ". /root/.nvm/nvm.sh && nvm install 14.17.3 && nvm use 14.17.3 && nvm alias default 14.17.3"
  cliworker:
    type: php:7.4
    composer_version: false
    via: cli
    command: sleep infinity
  custom:
    type: php:7.4
    composer_version: 2-latest
    via: nginx
    ssl: true
    webroot: web
    xdebug: true
    config:
      php: config/php.ini
    overrides:
      image: devwithlando/php:7.4-fpm-5
      environment:
        DUALBLADE: maxim
        OTHER: thing
  custom_nginx:
    build_as_root:
      - apt-get update -y
      - apt-get install curl -y
      - mkdir -p /app/test && touch /app/test/managed_build_step
    overrides:
      environment:
        MORE: things
        OTHER: stuff
tooling:
  php:
    service: defaults
  node:
    service: :host
    cmd: /root/.nvm/versions/node/v14.17.3/bin/node
    options:
      host:
        description: The service to use
        default: cli
        alias:
          - h

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/php": ../..
