name: lando-php-edge82nginx
services:
  default:
    type: php:8.2
    composer_version: false
    via: nginx
    ssl: true
    overrides:
      image: devwithlando/php:8.2-fpm-4-edge

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/php": ../..
