name: lando-php-stable74nginx
services:
  default:
    type: php:7.4
    composer_version: false
    via: nginx
    ssl: true
    overrides:
      image: devwithlando/php:7.4-fpm-4

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/php": ./../../