name: lando-php-edge73nginx
services:
  default:
    type: php:7.3
    composer_version: false
    via: nginx
    ssl: true
    overrides:
      image: devwithlando/php:7.3-fpm-4-edge

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/php": ../..
