name: lando-php-stable73apache
services:
  default:
    type: php:7.3
    composer_version: false
    ssl: true
    overrides:
      image: devwithlando/php:7.3-apache-4

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/php": ./../../