name: lando-phpcomposer
services:
  php72:
    type: php:7.2
  php83:
    type: php:8.3
  nocomposer:
    type: php:8.3
    composer_version: false
  composer1:
    type: php:7.4
    composer_version: 1
  composer2:
    type: php:8.3
    composer_version: 2
  composer1latest:
    type: php:8.3
    composer_version: 1-latest
  composer2latest:
    type: php:8.3
    composer_version: 2-latest
  composer1ver:
    type: php:8.3
    composer_version: '1.10.21'
  composer2ver:
    type: php:8.3
    composer_version: '2.1.10'
  composer22:
    type: php:8.3
    composer_version: 2.2
  composer22latest:
    type: php
    composer_version: 2.2-latest
  composer22ver:
    type: php:8.3
    composer_version: '2.2.10'
  dependencies:
    type: php:8.3
    composer_version: 2
    composer:
      phpunit/phpunit: "*"

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/php": ../..
