name: lando-php-stable81apache
services:
  default:
    type: php:8.1
    composer_version: false
    ssl: true
    overrides:
      image: devwithlando/php:8.1-apache-4

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/php": ./../../