name: lando-php56
events:
  post-start:
    - defaults: php -i | grep memory_limit | grep -e "-1"
services:
  defaults:
    type: php:5.6
    composer_version: false
  cli:
    type: php:5.6
    composer_version: false
    via: cli
  cliworker:
    type: php:5.6
    composer_version: false
    via: cli
    command: sleep infinity
  custom:
    type: php:5.6
    composer_version: false
    via: nginx
    ssl: true
    webroot: web
    xdebug: true
    config:
      php: config/php.ini
    overrides:
      image: devwithlando/php:5.6-fpm-4
      environment:
        DUALBLADE: maxim
        OTHER: thing
  custom_nginx:
    build_as_root:
      - apt-get update -y
      - apt-get install curl -y
      - mkdir -p /app/test && touch /app/test/managed_build_step
    overrides:
      environment:
        MORE: things
        OTHER: stuff
tooling:
  php:
    service: defaults

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/php": ../..
